services:
  app:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run dev
    # Add these for better development experience
    stdin_open: true
    tty: true 