[build]
  base = "/"
  environment = { NODE_VERSION = "20" }

[dev]
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  external_node_modules = ["@sparticuz/chromium"]

[[plugins]]
  package = "./netlify-plugin-generate-functions"